version: 0.2

phases:
  install:
    commands:
      - node -v
      - npm -v
      - yarn -v

  pre_build:
    commands:
      - yarn install

  build:
    commands:
      - ./build.sh

  post_build:
    commands:
      - rm -rf node_modules/

artifacts:
  base-directory: "."
  files:
    - "**/*"
