version: 0.2

phases:
  install:
    commands:
      - echo Instalando as dependências...
      - npm install

  pre_build:
    commands:
      - echo Executando o script de build...
      - chmod +x ./build.sh
      - ./build.sh

  build:
    commands:
      - echo Iniciando a aplicação...
      - npm run dev

artifacts:
  files:
    - '**/*'
  discard-paths: yes