version: 0.2

phases:
  pre_build:
    commands:
      - echo Installando pacotes...
      - npm run dev
  build:
    commands:
      - echo Criando build...
      - ./build.sh  # Se o build.sh fizer o trabalho de construção, chame-o aqui.
  post_build:
    commands:
      - echo Removendo arquivos desnecessários...
      - rm -rf node_modules/
artifacts:
  base-directory: '.'
  files:
    - '**/*'
