version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm config set unsafe-perm true
      - npm install
  build:
    commands:
      - echo Create build...
      - npm run build
  post_build:
    commands:
      - echo Removing unnecessary files...
      - rm -rf node_modules/
      
artifacts:
  base-directory: '.'
  files:
    - '**/*'
